# [phases.setup]
# cmds = ['pnpm i']

# [phases.setup]
# cmds = ['npm i -g dotenv-cli wrangler']

[phases.install]
cmds = ['pnpm i']

[phases.build]
cmds = ['pnpm build']

[start]
cmd = 'pnpm start'

[variables]
NODE_ENV = 'production'