export const ecomApiSqlitelocalDbPath = "file:./ecom-api-sqlite.db";

export const ecomApiCuisines = {
    "burger": "Burger",
    "pizza": "Pizza",
    "fast-food": "Fast food",
    "coffee": "Coffee",
    "salads": "Salads",
    "sandwiches": "Sandwiches",
    "asian": "Asian",
    "breakfast": "Breakfast",
    "pasta": "Pasta",
    "sushi": "Sushi",
    "mexican": "Mexican",
    "italian": "Italian",
    "indian": "Indian",
    "chinese": "Chinese",
    "kebab": "Kebab",
    "seafood": "Seafood",
    "thai": "Thai",
    "american": "American",
    "vietnamese": "Vietnamese",
    "japanese": "Japanese",
    "turkish": "Turkish",
    "fish-chips": "Fish & Chips",
    "greek": "Greek",
    "french": "French",
    "caribbean": "Caribbean",
    "lebanese": "Lebanese",
    "north-indian": "North Indian",
    "spanish": "Spanish",
}