export const ecomApiSqlitelocalDbPath = "file:./ecom-api-sqlite.db";

export const ecomApiCuisines = [
    "Burger",
    "Pizza",
    "Fast food",
    "Coffee",
    "Salads",
    "Sandwiches",
    "Asian",
    "Breakfast",
    "Pasta",
    "Sushi",
    "Mexican",
    "Italian",
    "Indian",
    "Chinese",
    "Kebab",
    "Seafood",
    "Thai",
    "American",
    "Vietnamese",
    "Japanese",
    "Turkish",
    "Fish & Chips",
    "Greek",
    "French",
    "Caribbean",
    "Lebanese",
    "North Indian",
    "Spanish",
]