   name: Deploy to Ubuntu Server

   on:
     push:
       branches: [prod]

   concurrency:
     group: ${{ github.workflow }}-${{ github.ref }}
     cancel-in-progress: true

   jobs:
     deploy:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v3
         
         - name: SSH Deploy
           uses: appleboy/ssh-action@master
           with:
             host: ${{ secrets.SERVER_HOST }}
             username: ${{ secrets.SERVER_USER }}
             key: ${{ secrets.SSH_PRIVATE_KEY }}
             script: |
               cd ${{ secrets.APP_DIR }}
               
               # Discard any local changes before pulling 
               git reset --hard
               git clean -fd
               git pull origin prod
               
               # Get the current git commit hash
               GIT_HASH=$(git rev-parse HEAD)
            
               # Set system-wide environment variables
               echo 'export DOTENV_PRIVATE_KEY_PRODUCTION="${{ secrets.DOTENV_PRIVATE_KEY_PRODUCTION }}"' | sudo tee /etc/profile.d/app_env.sh
               echo 'export SOURCE_COMMIT="'$GIT_HASH'"' | sudo tee -a /etc/profile.d/app_env.sh
               sudo chmod +x /etc/profile.d/app_env.sh
               # Reload environment variables for current session
               source /etc/profile.d/app_env.sh

               pnpm i
               pnpm run build
               pnpm start