   name: Deploy to Ubuntu Server

   on:
     push:
       branches: [prod]

   jobs:
     deploy:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v3
         
         - name: SSH Deploy
           uses: appleboy/ssh-action@master
           with:
             host: ${{ secrets.SERVER_HOST }}
             username: ${{ secrets.SERVER_USER }}
             key: ${{ secrets.SSH_PRIVATE_KEY }}
             script: |
               cd ${{ secrets.APP_DIR }}
               git pull origin prod

            
               # Set system-wide environment variable
               echo 'export DOTENV_PRIVATE_KEY_PRODUCTION="${{ secrets.DOTENV_PRIVATE_KEY_PRODUCTION }}"' | sudo tee /etc/profile.d/app_env.sh
               sudo chmod +x /etc/profile.d/app_env.sh
               # Reload environment variables for current session
               source /etc/profile.d/app_env.sh


               pnpm i
               pnpm run build
              #  pnpm run cf:pages:deploy
              #  pnpm start